### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kalynrobinson** [kalynrobinson/xf2_ajax_paging#1]
# Jump Page
- [x] Doesn't actually work

# SEO Friendliness
- [x] Update canonical, next, and previous URLs in head when page changes
- [x] Push new state to history when page changes
- [x] Add href back to pagers

# Optimization
- [x] See where JQuery queries can be reduced or cached
